name             'indexador'
maintainer       'AMVIAR'
maintainer_email 'anero79@gmail.com'
description      'Provisioning de ambiente de desarrollo para el indexador'
long_description 'Provisioning de ambiente de desarrollo para el indexador'
version          '0.0.1'

depends   'apt'
depends   'ssh_known_hosts'
depends   'rvm'
depends   'mongodb'